### PR TITLE
Fix json file not exist error

### PR DESCRIPTION
**Pull request by theowenyoung**
Hi, I found the error reason. By the doc https://actionsflow.github.io/docs/workflow/#ontriggerconfigexportoutputs

if we use `exportOutputs`, we should bind the host files to docker container.

Now it's ok!

### CODE REVIEW

**Comment by Industrial** [comment]
Cool, thanks a lot! Should this change go into the actionsflow repo as well? Or in to the example from which I cloned my repo?

**Comment by theowenyoung** [comment]
I'm afraid not, cause `puppeteer` is only used in `Reddit` trigger, and `exportOutputs` is not commonly used, so `using: local` is very slow than the default config.

so, I think for most use cases, the default config is just fine.

**Comment by Industrial** [comment]
@theowenyoung, you set the `rss.yml` to `active: false` which disables it. I still get the same error with the `reddit-stocks.yml`.

**Comment by theowenyoung** [comment]
I see https://github.com/Industrial/configuration-actionsflow/actions/runs/1628718450  works well, can you give the action log link?

**Comment by Industrial** [comment]
I'm not running these actions on github, but locally with docker.

I've added https://github.com/Industrial/configuration-actionsflow/blob/main/bin/start which starts it with docker.


This is what happens when I run the command:

```
Actionsflow CLI version: 1.12.0

[00:30:08] INFO actionsflow: Start server at http://localhost:3000
[00:30:08] INFO actionsflow: Listen webhook endpoint at http://localhost:3000/webhook/
[00:30:08] INFO actionsflow: Start cron tasks
[00:30:08] INFO actionsflow: Clean the dest folder dist/.cron/1640651408383
[00:30:08] INFO actionsflow: There are 3 immediate tasks, 0 delay tasks
[00:30:09] INFO actionsflow: Run 3 immediate tasks finished, wait for 0 delay tasks to finish...
[00:30:09] INFO actionsflow: All tasks finished, wait for building...
[00:30:09] INFO actionsflow: No new updates found at trigger [reddit] of workflow [reddit-news.yml], skip it.
[00:30:09] INFO actionsflow: No new updates found at trigger [rss] of workflow [rss.yml], skip it.
[00:30:09] INFO actionsflow: Actionsflow build finished with the following errors:
[00:30:09] INFO actionsflow: When running trigger [reddit] of workflow file [reddit-stocks.yml]:  Error: Failed to launch the browser process!
/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
    at Interface.emit (events.js:388:22)
    at Interface.close (readline.js:429:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
UNHANDLED REJECTION TriggersError: Multiple Errors when running triggers
    at build (/usr/local/lib/node_modules/actionsflow/dist/src/build.js:242:15)
    at async runWorkflows (/usr/local/lib/node_modules/actionsflow/dist/src/run-workflows.js:18:5)
    at async /usr/local/lib/node_modules/actionsflow/dist/src/cron.js:13:13 {
  errors: [
    {
      error: Error: Failed to launch the browser process!
      /usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory


      TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

          at onClose (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
          at Interface.<anonymous> (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
          at Interface.emit (events.js:388:22)
          at Interface.close (readline.js:429:8)
          at Socket.onend (readline.js:202:10)
          at Socket.emit (events.js:388:22)
          at endReadableNT (internal/streams/readable.js:1336:12)
          at processTicksAndRejections (internal/process/task_queues.js:82:21),
      trigger: [Object],
      workflow: [Object]
    }
  ]
}
^C[00:30:10] INFO actionsflow:
Stopping actionflow...
```

**Comment by theowenyoung** [comment]
Have you `npm install`?

and just run `npm start` locally.

**Comment by theowenyoung** [comment]
or `npm run build` and `npm run act`

**Comment by theowenyoung** [comment]
I test it locally just now, it works fine.

**Comment by Industrial** [comment]
My bad. It works! Thanks a lot :)

**Pull request merged**
